- hosts: dev
  sudo: true
  gather_facts: true
  vars_files:
    - "vars/dev.yml"
  roles:
#    - initial
#    - ntpd
    - apache2
#    - xdebug
#    - composer
    - mariadb-10-1
    - phpmyadmin
#    - finally
